# This script deploys your website automatically
name: Github Pages

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm install --legacy-peer-deps 
           git config --global user.name 'abubakar-siddiqui'
           git remote set-url origin https://${{ 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 }}@github.com:Abubakar-Siddiqui/notes_app_react.git
           npm run deploy
